; SenseCAP Indicator RP2040 firmware
;
; Build:   pio run
; Upload:  pio run -t upload
; Monitor: pio device monitor

[env:indicator_rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = seeed_indicator_rp2040
framework = arduino
board_build.core = earlephilhower

monitor_speed = 115200
upload_port = /dev/cu.usbmodem*

lib_deps =
    bakercp/PacketSerial@^1.4.0
    dvarrel/AHT20@^1.0.2
    sensirion/Sensirion I2C SCD4x@^1.1.0
    sensirion/Sensirion I2C SGP40@^0.1.0
    sensirion/Sensirion Gas Index Algorithm@^3.2.3

build_flags =
    -DPKT_SEND_INTERVAL_MS=5000
