// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: indicator_ha

#include "../ui.h"

void ui_comp_screen_sensor_create_hook(lv_obj_t * comp)
{
}

void ui_comp_screen_setting_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Screen_wifi_create_hook(lv_obj_t * comp)
{
}
