// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: indicator_ha

#include "../ui.h"

void ui_screen_wifi_screen_init(void)
{
    ui_screen_wifi = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screen_wifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_panel_top_5 = lv_obj_create(ui_screen_wifi);
    lv_obj_set_width(ui_panel_top_5, 480);
    lv_obj_set_height(ui_panel_top_5, 85);
    lv_obj_set_align(ui_panel_top_5, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_panel_top_5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panel_top_5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_top_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_top_5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel_top_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_back_wifi = lv_btn_create(ui_panel_top_5);
    lv_obj_set_width(ui_back_wifi, 100);
    lv_obj_set_height(ui_back_wifi, 50);
    lv_obj_set_x(ui_back_wifi, -15);
    lv_obj_set_y(ui_back_wifi, 0);
    lv_obj_add_flag(ui_back_wifi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_back_wifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_back_wifi, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_back_wifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_back_wifi, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_screen_home_data_label4 = lv_label_create(ui_panel_top_5);
    lv_obj_set_width(ui_screen_home_data_label4, 316);
    lv_obj_set_height(ui_screen_home_data_label4, 21);
    lv_obj_set_align(ui_screen_home_data_label4, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_screen_home_data_label4, "Wi-Fi");
    lv_obj_set_style_text_color(ui_screen_home_data_label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_screen_home_data_label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_screen_home_data_label4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_screen_home_data_label4, &ui_font_font0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi__st_button_ha_data4 = lv_btn_create(ui_panel_top_5);
    lv_obj_set_width(ui_wifi__st_button_ha_data4, 60);
    lv_obj_set_height(ui_wifi__st_button_ha_data4, 60);
    lv_obj_set_align(ui_wifi__st_button_ha_data4, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_wifi__st_button_ha_data4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wifi__st_button_ha_data4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifi__st_button_ha_data4, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifi__st_button_ha_data4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_wifi__st_button_ha_data4, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi_st_7 = lv_img_create(ui_wifi__st_button_ha_data4);
    lv_img_set_src(ui_wifi_st_7, &ui_img_wifi_disconet_png);
    lv_obj_set_width(ui_wifi_st_7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifi_st_7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifi_st_7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifi_st_7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifi_st_7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
