// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: indicator_ha

#include "../ui.h"

void ui_screen_ha_ctrl_screen_init(void)
{
    ui_screen_ha_ctrl = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screen_ha_ctrl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_switch4 = lv_btn_create(ui_screen_ha_ctrl);
    lv_obj_set_width(ui_switch4, 214);
    lv_obj_set_height(ui_switch4, 164);
    lv_obj_set_x(ui_switch4, 22);
    lv_obj_set_y(ui_switch4, 96);
    lv_obj_add_flag(ui_switch4, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_switch4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_switch4, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_switch4, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_switch4, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_switch4, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_switch4_logo1 = lv_img_create(ui_switch4);
    lv_img_set_src(ui_switch4_logo1, &ui_img_ic_switch2_off_png);
    lv_obj_set_width(ui_switch4_logo1, LV_SIZE_CONTENT);   /// 45
    lv_obj_set_height(ui_switch4_logo1, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_x(ui_switch4_logo1, 0);
    lv_obj_set_y(ui_switch4_logo1, -10);
    lv_obj_set_align(ui_switch4_logo1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_switch4_logo1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_switch4_logo1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_switch4_label1 = lv_label_create(ui_switch4);
    lv_obj_set_width(ui_switch4_label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_switch4_label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_switch4_label1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_switch4_label1, "Switch4");
    lv_obj_set_style_text_color(ui_switch4_label1, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_switch4_label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_switch4_label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switch5 = lv_obj_create(ui_screen_ha_ctrl);
    lv_obj_set_width(ui_switch5, 214);
    lv_obj_set_height(ui_switch5, 164);
    lv_obj_set_x(ui_switch5, 244);
    lv_obj_set_y(ui_switch5, 96);
    lv_obj_clear_flag(ui_switch5, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_radius(ui_switch5, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_switch5, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_switch5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_switch5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_switch5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switch5_arc1 = lv_arc_create(ui_switch5);
    lv_obj_set_width(ui_switch5_arc1, 130);
    lv_obj_set_height(ui_switch5_arc1, 125);
    lv_obj_set_align(ui_switch5_arc1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_switch5_arc1, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_clear_flag(ui_switch5_arc1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_value(ui_switch5_arc1, 70);
    lv_arc_set_bg_angles(ui_switch5_arc1, 140, 40);
    lv_obj_set_style_arc_color(ui_switch5_arc1, lv_color_hex(0x1C1C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_switch5_arc1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_switch5_arc1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_switch5_arc1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_switch5_arc1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_switch5_arc1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_switch5_arc1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_switch5_arc1, lv_color_hex(0x529D53), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_switch5_arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_switch5_arc1, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_switch5_arc1, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_switch5_arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch5_arc1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_switch5_label1 = lv_label_create(ui_switch5_arc1);
    lv_obj_set_width(ui_switch5_label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_switch5_label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_switch5_label1, 0);
    lv_obj_set_y(ui_switch5_label1, -5);
    lv_obj_set_align(ui_switch5_label1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_switch5_label1, "Switch5");
    lv_obj_set_style_text_color(ui_switch5_label1, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_switch5_label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_switch5_label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switch5_arc_data1 = lv_label_create(ui_switch5_arc1);
    lv_obj_set_width(ui_switch5_arc_data1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_switch5_arc_data1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_switch5_arc_data1, 0);
    lv_obj_set_y(ui_switch5_arc_data1, -50);
    lv_obj_set_align(ui_switch5_arc_data1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_switch5_arc_data1, "70 °C");
    lv_obj_set_style_text_color(ui_switch5_arc_data1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_switch5_arc_data1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_switch5_arc_data1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switch6 = lv_btn_create(ui_screen_ha_ctrl);
    lv_obj_set_width(ui_switch6, 214);
    lv_obj_set_height(ui_switch6, 78);
    lv_obj_set_x(ui_switch6, 22);
    lv_obj_set_y(ui_switch6, 268);
    lv_obj_add_flag(ui_switch6, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_switch6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_switch6, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_switch6, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_switch6, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_switch6, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_switch6_logo1 = lv_img_create(ui_switch6);
    lv_img_set_src(ui_switch6_logo1, &ui_img_ic_switch1_off_png);
    lv_obj_set_x(ui_switch6_logo1, 120);
    lv_obj_set_y(ui_switch6_logo1, 2);
    lv_obj_add_flag(ui_switch6_logo1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_switch6_logo1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_switch6_label1 = lv_label_create(ui_switch6);
    lv_obj_set_width(ui_switch6_label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_switch6_label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_switch6_label1, 16);
    lv_obj_set_y(ui_switch6_label1, 22);
    lv_label_set_text(ui_switch6_label1, "Switch6");
    lv_obj_set_style_text_color(ui_switch6_label1, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_switch6_label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_switch6_label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switch7 = lv_btn_create(ui_screen_ha_ctrl);
    lv_obj_set_width(ui_switch7, 214);
    lv_obj_set_height(ui_switch7, 78);
    lv_obj_set_x(ui_switch7, 244);
    lv_obj_set_y(ui_switch7, 268);
    lv_obj_add_flag(ui_switch7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_switch7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_switch7, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_switch7, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switch7_label1 = lv_label_create(ui_switch7);
    lv_obj_set_width(ui_switch7_label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_switch7_label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_switch7_label1, 16);
    lv_obj_set_y(ui_switch7_label1, 22);
    lv_label_set_text(ui_switch7_label1, "Switch7");
    lv_obj_set_style_text_color(ui_switch7_label1, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_switch7_label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_switch7_label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switch7_switch1 = lv_switch_create(ui_switch7);
    lv_obj_set_width(ui_switch7_switch1, 60);
    lv_obj_set_height(ui_switch7_switch1, 28);
    lv_obj_set_x(ui_switch7_switch1, 115);
    lv_obj_set_y(ui_switch7_switch1, 20);
    lv_obj_add_state(ui_switch7_switch1, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_radius(ui_switch7_switch1, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_switch7_switch1, 40, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_switch7_switch1, lv_color_hex(0x4F4F4F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch7_switch1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_switch7_switch1, lv_color_hex(0x529D53), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_switch7_switch1, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_switch8 = lv_btn_create(ui_screen_ha_ctrl);
    lv_obj_set_width(ui_switch8, 440);
    lv_obj_set_height(ui_switch8, 78);
    lv_obj_set_x(ui_switch8, 22);
    lv_obj_set_y(ui_switch8, 360);
    lv_obj_add_flag(ui_switch8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_switch8, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_switch8, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_switch8, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switch8_label1 = lv_label_create(ui_switch8);
    lv_obj_set_width(ui_switch8_label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_switch8_label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_switch8_label1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_switch8_label1, "Switch8");
    lv_obj_set_style_text_color(ui_switch8_label1, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_switch8_label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_switch8_label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switch8_slider1 = lv_slider_create(ui_switch8);
    lv_slider_set_value(ui_switch8_slider1, 80, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_switch8_slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_switch8_slider1, 0,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(ui_switch8_slider1, 385);
    lv_obj_set_height(ui_switch8_slider1, 20);
    lv_obj_set_x(ui_switch8_slider1, 12);
    lv_obj_set_y(ui_switch8_slider1, 12);
    lv_obj_set_style_radius(ui_switch8_slider1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_switch8_slider1, lv_color_hex(0x1C1C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch8_slider1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_switch8_slider1, lv_color_hex(0x529D53), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch8_slider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_switch8_slider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch8_slider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_panel_top_3 = lv_obj_create(ui_screen_ha_ctrl);
    lv_obj_set_width(ui_panel_top_3, 480);
    lv_obj_set_height(ui_panel_top_3, 100);
    lv_obj_set_align(ui_panel_top_3, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_panel_top_3, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_panel_top_3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_panel_top_3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_top_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_top_3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel_top_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time_ha_data2 = lv_label_create(ui_panel_top_3);
    lv_obj_set_width(ui_time_ha_data2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time_ha_data2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time_ha_data2, 15);
    lv_obj_set_y(ui_time_ha_data2, 0);
    lv_obj_set_align(ui_time_ha_data2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_time_ha_data2, "21:20");
    lv_obj_set_style_text_font(ui_time_ha_data2, &ui_font_font0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_screen_home_data_label3 = lv_label_create(ui_panel_top_3);
    lv_obj_set_width(ui_screen_home_data_label3, 316);
    lv_obj_set_height(ui_screen_home_data_label3, 21);
    lv_obj_set_align(ui_screen_home_data_label3, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_screen_home_data_label3, "Home Assistant Control\n");
    lv_obj_set_style_text_color(ui_screen_home_data_label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_screen_home_data_label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_screen_home_data_label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_screen_home_data_label3, &ui_font_font0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi__st_button_ha_data2 = lv_btn_create(ui_panel_top_3);
    lv_obj_set_width(ui_wifi__st_button_ha_data2, 60);
    lv_obj_set_height(ui_wifi__st_button_ha_data2, 60);
    lv_obj_set_align(ui_wifi__st_button_ha_data2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_wifi__st_button_ha_data2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wifi__st_button_ha_data2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifi__st_button_ha_data2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifi__st_button_ha_data2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_wifi__st_button_ha_data2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi_st_5 = lv_img_create(ui_wifi__st_button_ha_data2);
    lv_img_set_src(ui_wifi_st_5, &ui_img_wifi_disconet_png);
    lv_obj_set_width(ui_wifi_st_5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifi_st_5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifi_st_5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifi_st_5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifi_st_5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_switch4, ui_event_switch4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_switch5_arc1, ui_event_switch5_arc1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_switch6, ui_event_switch6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifi__st_button_ha_data2, ui_event_wifi__st_button_ha_data2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screen_ha_ctrl, ui_event_screen_ha_ctrl, LV_EVENT_ALL, NULL);

}
