// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: indicator_ha

#include "../ui.h"

void ui_screen_broker_screen_init(void)
{
    ui_screen_broker = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screen_broker, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_panel_top_6 = lv_obj_create(ui_screen_broker);
    lv_obj_set_width(ui_panel_top_6, 480);
    lv_obj_set_height(ui_panel_top_6, 85);
    lv_obj_set_align(ui_panel_top_6, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_panel_top_6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panel_top_6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_top_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panel_top_6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panel_top_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_back_wifi1 = lv_btn_create(ui_panel_top_6);
    lv_obj_set_width(ui_back_wifi1, 100);
    lv_obj_set_height(ui_back_wifi1, 50);
    lv_obj_set_x(ui_back_wifi1, -15);
    lv_obj_set_y(ui_back_wifi1, 0);
    lv_obj_add_flag(ui_back_wifi1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_back_wifi1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_back_wifi1, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_back_wifi1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_back_wifi1, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_screen_home_data_label5 = lv_label_create(ui_panel_top_6);
    lv_obj_set_width(ui_screen_home_data_label5, 316);
    lv_obj_set_height(ui_screen_home_data_label5, 21);
    lv_obj_set_align(ui_screen_home_data_label5, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_screen_home_data_label5, "MQTT");
    lv_obj_set_style_text_color(ui_screen_home_data_label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_screen_home_data_label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_screen_home_data_label5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_screen_home_data_label5, &ui_font_font0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi__st_button_ha_data3 = lv_btn_create(ui_panel_top_6);
    lv_obj_set_width(ui_wifi__st_button_ha_data3, 60);
    lv_obj_set_height(ui_wifi__st_button_ha_data3, 60);
    lv_obj_set_align(ui_wifi__st_button_ha_data3, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_wifi__st_button_ha_data3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wifi__st_button_ha_data3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifi__st_button_ha_data3, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifi__st_button_ha_data3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_wifi__st_button_ha_data3, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi_st_1 = lv_img_create(ui_wifi__st_button_ha_data3);
    lv_img_set_src(ui_wifi_st_1, &ui_img_wifi_disconet_png);
    lv_obj_set_width(ui_wifi_st_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifi_st_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifi_st_1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifi_st_1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifi_st_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_container_Inputer = lv_obj_create(ui_screen_broker);
    lv_obj_remove_style_all(ui_container_Inputer);
    lv_obj_set_width(ui_container_Inputer, 420);
    lv_obj_set_height(ui_container_Inputer, 160);
    lv_obj_set_x(ui_container_Inputer, 0);
    lv_obj_set_y(ui_container_Inputer, 120);
    lv_obj_set_align(ui_container_Inputer, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_container_Inputer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_container_Inputer);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 46);
    lv_obj_set_y(ui_Label2, 1);
    lv_obj_set_align(ui_Label2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label2, "mqtt://");

    ui_Label3 = lv_label_create(ui_container_Inputer);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -13);
    lv_obj_set_y(ui_Label3, -60);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Home Assistant address");

    ui_textarea_ip_0 = lv_textarea_create(ui_container_Inputer);
    lv_obj_set_width(ui_textarea_ip_0, 155);
    lv_obj_set_height(ui_textarea_ip_0, LV_SIZE_CONTENT);    /// 47
    lv_obj_set_x(ui_textarea_ip_0, -23);
    lv_obj_set_y(ui_textarea_ip_0, 0);
    lv_obj_set_align(ui_textarea_ip_0, LV_ALIGN_CENTER);
    if("0123456789." == "") lv_textarea_set_accepted_chars(ui_textarea_ip_0, NULL);
    else lv_textarea_set_accepted_chars(ui_textarea_ip_0, "0123456789.");
    lv_textarea_set_max_length(ui_textarea_ip_0, 20);
    lv_textarea_set_placeholder_text(ui_textarea_ip_0, "192.168.1.1");
    lv_textarea_set_one_line(ui_textarea_ip_0, true);



    ui_Label4 = lv_label_create(ui_container_Inputer);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 84);
    lv_obj_set_y(ui_Label4, 0);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, ":1883");

    ui_Button1 = lv_btn_create(ui_container_Inputer);
    lv_obj_set_width(ui_Button1, 94);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 163);
    lv_obj_set_y(ui_Button1, 0);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x4AAEE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Confirm");

    ui_Container2 = lv_obj_create(ui_screen_broker);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 100);
    lv_obj_set_height(ui_Container2, 50);
    lv_obj_set_x(ui_Container2, 118);
    lv_obj_set_y(ui_Container2, 173);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard_ip = lv_keyboard_create(ui_screen_broker);
    lv_keyboard_set_mode(ui_Keyboard_ip, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard_ip, 480);
    lv_obj_set_height(ui_Keyboard_ip, 240);
    lv_obj_set_align(ui_Keyboard_ip, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard_ip, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_back_wifi1, ui_event_back_wifi1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifi__st_button_ha_data3, ui_event_wifi__st_button_ha_data3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_textarea_ip_0, ui_event_textarea_ip_0, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard_ip, ui_textarea_ip_0);
    lv_obj_add_event_cb(ui_Keyboard_ip, ui_event_Keyboard_ip, LV_EVENT_ALL, NULL);

}
