// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: indicator_ha

#include "ui.h"
#include "view_data.h"

static char* TAG = "ui_events";

void switch_event_cb(lv_event_t* e) {
	// lv_event_code_t event_code = lv_event_get_code(e);
	lv_obj_t* target = lv_event_get_target(e);

	bool status = lv_obj_has_state(target, LV_STATE_CHECKED);

	struct view_data_ha_switch_data switch_data = {0};

	if(status)
	{
		switch_data.value = 1;
	}
	else
	{
		switch_data.value = 0;
	}

	if(target == ui_switch1)
	{
		switch_data.index = 0;
	}
	else if(target == ui_switch2)
	{
		switch_data.index = 1;
	}
	else if(target == ui_switch3)
	{
		switch_data.index = 2;
	}
	else if(target == ui_switch4)
	{
		switch_data.index = 3;
	}
	else if(target == ui_switch6)
	{
		switch_data.index = 5;
	}
	else if(target == ui_switch7)
	{
		switch_data.index = 6;
	}
	else
	{
		switch_data.index = -1;
	}

	ESP_LOGI(TAG, " switch%d: %d", switch_data.index + 1, switch_data.value);
	esp_event_post_to(view_event_handle, VIEW_EVENT_BASE,
					  VIEW_EVENT_HA_SWITCH_ST, &switch_data,
					  sizeof(switch_data), portMAX_DELAY);
}

void switch_arc_event_cb(lv_event_t* e) {
	lv_obj_t* target = lv_event_get_target(e);
	lv_arc_t* tr_arc = (lv_arc_t*)target;

	int value = (int)tr_arc->value;

	char buf[16];
	sprintf(buf, "%d", value);

	struct view_data_ha_switch_data switch_data = {0};

	switch_data.value = value;

	if(target == ui_switch5_arc1)
	{
		switch_data.index = 4;
	}
	else if(target == ui_switch8_slider1)
	{
		switch_data.index = 7;
	}

	ESP_LOGI(TAG, " switch%d: %d", switch_data.index + 1, switch_data.value);
	esp_event_post_to(view_event_handle, VIEW_EVENT_BASE,
					  VIEW_EVENT_HA_SWITCH_ST, &switch_data,
					  sizeof(switch_data), portMAX_DELAY);
}
